from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

urlpatterns = [
    path('', Home,name='home'),
    path('login/', Login,name='login'),
    path('logout/', Logout, name='logout'),
    path('register/', Register,name='register'),
    path('profile/<int:id>/', Profile,name='profile'),
    path('profile/edit/<int:id>/', edit_profile,name='edit_profile'),
    path('select/', Select,name='select'),
    path('select_report/', Select_report,name='select_report'),
    path('research_project/', Research_project,name='research_project'),
    path('research/', Research,name='research'),
    path('academic/', Academic,name='academic'),
    path('performance/', Performance,name='performance'),
    path ('mou/', Mou_form, name='mou'),
    path('researcher_report/', Researcher_report,name='researcher_report'),
    path('research_project_report/', Research_project_report,name='research_project_report'),
    path('research_report/', Research_report,name='research_report'),
    path('performance_report/', Performance_report,name='performance_report'),
    path('academic_report/', Academic_report,name='academic_report'),
    path('mou_report/', Mou_report,name='mou_report'),
    path('mou_detail/<int:id>/', Mou_detail, name='mou_detail'),
    path('research_detail/<int:id>/', Research_detail, name='research_detail'),
    path('research_project_detail/<int:id>/', Research_project_detail, name='research_project_detail'),
    path('performance_detail/<int:id>/', Performance_detail,name='performance_detail'),
    path('academic_detail/<int:id>/', Academic_detail,name='academic_detail'),
    path('api/departments/', get_departments, name='get_departments'),
    path('delete_fund/<int:fund_id>/', delete_fund, name='delete_fund'),
    path('delete_agency/<int:agency_id>/', delete_agency, name='delete_agency'),
    path('research_project/edit/<int:id>/', edit_research_project, name='edit_research_project'),
    path('research/edit/<int:id>/', edit_research, name='edit_research'),
    path('researchperformance/edit/<int:id>/', edit_researchperformance, name='edit_researchperformance'),
    path('academic/edit/<int:id>/', edit_academic, name='edit_academic'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='login/password_reset_form.html'),name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset_confirm.html"),name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'),name='password_reset_complete'),
    path('get-provinces/', get_provinces, name='get_provinces'),
    path('get-districts/', get_districts, name='get_districts'),
    path('districts-by-subdistrict/', districts_by_subdistrict, name='districts_by_subdistrict'),
    path('provinces-by-district/', provinces_by_district, name='provinces_by_district'),
]
